[project]
name = "flan-t5-custom-kserve-engine"
version = "0.1.0"
description = "Custom KServe Serving Engine to serve a FLAN-T5 model via OCP Model Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kserve>=0.16.0",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
